### ISSUE TITLE
As a fisher, I can look for rafts in an area.

### ISSUE THREAD

**Issue by AlbertGrimley** [smelts-tech/ropeless_web#10]
Enter lat and long and then select from a radius dropdown containing 1/2 mile increments up to 10 miles.

As a fisher, I can see all of the rafts, but I can't see whose rafts they are.

**Comment by AlbertGrimley** [comment]
This page will later contain a map showing device location.

**Comment by fermion** [comment]
Would it be easier for users if this just showed a map with the last known location for the trap? We could make the initial bounding box big enough to fit each of the traps. Clicking one could show an info window or something.

**Comment by AlbertGrimley** [comment]
This feature is a filter option on the existing page.  It will narrow the list of devices.  Later, when we have mapping capability, the devices could be shown on a map.

**Comment by fermion** [comment]
I guess I'm questioning how readily users will know a latitude/longitude pair to search near. If that's something commonly known maybe my concerns are moot.

**Comment by AlbertGrimley** [comment]
It's in the requirements doc.  🤷‍♂️

**Comment by fermion** [comment]
Sure, but that doesn't mean that it's the best UX! We should at least confirm that imho.

**Comment by AlbertGrimley** [comment]
On it.
