### ISSUE TITLE
As a federal agency user, I can specify a time frame (start and end date) and query the list of rafts that had device events in the timeframe.

### ISSUE THREAD

**Issue by AlbertGrimley** [smelts-tech/ropeless_web#11]

**Comment by fermion** [comment]
What's the view of this? HTML table? Any CSV export?

**Comment by AlbertGrimley** [comment]
This is a table on the page.  No export.

**Comment by inlovewithwhales2020** [comment]
@AlbertGrimley we need a date field where the user can enter the date directly or use a calendar for the user to choose start and end dates.
