### ISSUE TITLE
Allow users of the site to see raft locations

### ISSUE THREAD

**Issue by AlbertGrimley** [smelts-tech/ropeless_web#16]
* users will enter lat and long and then select from a radius dropdown containing 1/2 mile increments up to 10 miles
* as an agency, I can look for rafts in an area and see who they belong to
* as a fisher, I can see all of the rafts but _not_ who they belong to

**Comment by fermion** [comment]
What does an agency user see? Do they see the same as a fisher, all rafts and who they belong to?

**Comment by AlbertGrimley** [comment]
Yes.  They will both see all rafts.  Agency will see who all rafts belong to.  Fisher will see which ones belong to them, but others will be anonymous.
