### ISSUE TITLE
As a fisher, I receive an email with permission to create an account

### ISSUE THREAD

**Issue by inlovewithwhales2020** [smelts-tech/ropeless_web#29]
The email can be simple -- a welcome sentence and then the URL to the account creation form.

**Comment by fermion** [comment]
The way it's implemented now fishers and agency users can give us all of their information up front. After being approved they'll have full access to the system. They'll be unable to see/do anything until approval. All of this is being tracked in https://github.com/smelts-tech/ropeless_web/issues/12.
